version: "3.9"
services: 
    web:
        build:
            context: .
            dockerfile: dev.Dockerfile
        ports:
            - "8080:8080"
        environment:
            APP_ENVIRONMENT: prod
            SQL_CONNECTION_URL: postgres://postgres:password@sql:5432/?sslmode=disable
            MQ_CONNECTION_URL: amqp://mq:5672 
    sql: 
        image: "postgres:alpine"
        environment:
            POSTGRES_PASSWORD: password 
        ports:
            - "5432:5432"
    mq:
        image: "rabbitmq:alpine"
        ports: 
            - "5672:5672"